name: Python CI
on:
  push:
    branches:
      - master
      - main
      - "releases/**"
      - "!releases/**-alpha"
  pull_request:
    branches:
      - master
      - main
      - "releases/**"
      - "!releases/**-alpha"
  release:
    types: [created]
  workflow_dispatch:

jobs:
  validation:
    uses: microsoft/action-python/.github/workflows/validation.yml@0.6.4
    with:
      workdir: '.'

  publish:
    uses: microsoft/action-python/.github/workflows/publish.yml@0.6.4
    secrets:
      PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      TEST_PYPI_PASSWORD: ${{ secrets.TEST_PYPI_PASSWORD  }}
