name: Release

on:
  push:
    branches: [master, main]
    tags:
      - "*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
        matrix:
            python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"] # quotation marks are mandatory
    env:
      PYTHONUSING_COVERAGE: "3.9"

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4.1.1

      - name: Set up Python
        uses: actions/setup-python@v5.0.0
        with:
            python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          make deps

      - name: Run tox
        run: |
          make tox

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3.1.4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  publish:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4.1.1

      - name: Set up Python
        uses: actions/setup-python@v5.0.0
        with:
          python-version: '3.7'

      - name: Install dependencies
        run: |
          make deps

      - name: Publish Python 🐍 distribution 📦 to PyPI and PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          make publish

  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs:
      - publish
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4.1.1

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1.1.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
